; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9E8FFC09-9930-4160-9A99-3B5F42F358DF}
AppName=BNT ANDROID  TOOLS
AppVersion=8.11
;AppVerName=BNT ANDROID  TOOLS 7.0
AppPublisher=bntworxtv.com
AppPublisherURL=https://www.bntworxtv.com
AppSupportURL=https://www.bntworxtv.com
AppUpdatesURL=https://www.bntworxtv.com
DefaultDirName={autopf}\BNT ANDROID  TOOLS
DisableDirPage=yes
UninstallDisplayIcon={app}\BntAndroidTools.exe
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\NICOLITES\Desktop\android\installer
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\NICOLITES\Desktop\android\bnticon.ico
Password=Secret911@
Encryption=yes
SolidCompression=yes
WizardStyle=modern windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\NICOLITES\Desktop\android\BntAndroidTools.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\NICOLITES\Desktop\android\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\BNT ANDROID  TOOLS"; Filename: "{app}\BntAndroidTools.exe"; IconFilename: "{app}\bnticon.ico"
Name: "{autodesktop}\BNT ANDROID  TOOLS"; Filename: "{app}\BntAndroidTools.exe"; IconFilename: "{app}\bnticon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\BntAndroidTools.exe"; Description: "{cm:LaunchProgram,BNT ANDROID  TOOLS}"; Flags: nowait postinstall skipifsilent

